Added caching of weather data
osoc22/project-idlab pull request #76
Opened 2022-07-25 19:09 UTC by Matei9721

If we don't cache(save) the weather data after the first API call we would have to wait for a *very* long time every time we switch the calendar views.

2022-07-25 19:22 UTC, yustarandomname commented
And linter throws an error. But we will fix this tomorrow. 🌈 work life balance 😃

2022-07-26 07:24 UTC, Denperidge approved these changes

2022-07-26 07:31 UTC, DemianD commented on app/svelte/src/routes/upcomming.svelte
> +        const url = `https://idlab.osoc.be/weather/Brussels`;
Maybe we can make use of a environment variable for the link/host?

2022-07-26 07:31 UTC, DemianD commented on app/svelte/src/routes/upcomming.svelte
> +        console.log({response});
Console.log can be removed

2022-07-26 07:43 UTC, Matei9721 commented on app/svelte/src/routes/upcomming.svelte
> +        const url = `https://idlab.osoc.be/weather/Brussels`;
@abel2000 What do you think?

2022-07-26 08:01 UTC, yustarandomname requested changes

2022-07-26 08:01 UTC, yustarandomname commented on app/svelte/src/routes/upcomming.svelte
> +	let cachedWeather: any;
This should be more specifice, I will fix it

2022-07-26 08:06 UTC, yustarandomname approved these changes

2022-07-26 08:07 UTC, merged